spring:
  application:
    name: reservation-api
  profiles:
    default: dev
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      maximum-pool-size: 15
      minimum-idle: 10
      connection-timeout: 2000
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
